set(_CATKIN_CURRENT_PACKAGE "rmtt_teleop")
set(rmtt_teleop_VERSION "0.0.0")
set(rmtt_teleop_MAINTAINER "tianbot <tianbot@todo.todo>")
set(rmtt_teleop_PACKAGE_FORMAT "2")
set(rmtt_teleop_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_teleop_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_teleop_BUILDTOOL_DEPENDS "catkin")
set(rmtt_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(rmtt_teleop_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_teleop_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_teleop_TEST_DEPENDS )
set(rmtt_teleop_DOC_DEPENDS )
set(rmtt_teleop_URL_WEBSITE "")
set(rmtt_teleop_URL_BUGTRACKER "")
set(rmtt_teleop_URL_REPOSITORY "")
set(rmtt_teleop_DEPRECATED "")