arch:
    max_epochs: 120

checkpoint:
    # Folder where .ckpt files will be saved during training
    filepath: /workspace/packnet-sfm/results/chept
    save_top_k: -1

model:
    checkpoint_path: /workspace/packnet-sfm/results/chept/ruby-fog-15/epoch=35_optitrack_1-optitrack_1_part1-loss=0.000.ckpt
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # should be multiple of 32
        # image_shape: (352, 480)
        # image_shape: (384, 512)
        image_shape: (288, 384)
        # image_shape: (32, 32)

    train:
        batch_size: 8
        dataset: ['KITTI']
        path: ['/data/datasets/tello/aigc',
               '/data/datasets/tello/aigc',
               '/data/datasets/tello/aigc',
               '/data/datasets/tello/aigc',
               '/data/datasets/tello/aigc',

               '/data/datasets/tello/jw_dh_desk',
               '/data/datasets/tello/jw_dh_desk',
               '/data/datasets/tello/jw_dh_desk',
               '/data/datasets/tello/jw_dh_desk',
               
               '/data/datasets/tello/my_desk',
               '/data/datasets/tello/my_desk',
               
               '/data/datasets/tello/workbench_boxes_low_alt',
               '/data/datasets/tello/workbench_boxes_low_alt',
               
               '/data/datasets/tello/workbench_boxes_low_alt_2',
               '/data/datasets/tello/workbench_boxes_low_alt_2',
               
               '/data/datasets/tello/workbench_with_boxes',
               '/data/datasets/tello/workbench_with_boxes',
               '/data/datasets/tello/workbench_with_boxes',
               
               '/data/datasets/tello/optitrack_1',

               '/data/datasets/tello/optitrack_2',
               '/data/datasets/tello/optitrack_2',

               '/data/datasets/tello/optitrack_3',


               '/data/datasets/tello/optitrack_4',

               '/data/datasets/tello/optitrack_5',
               '/data/datasets/tello/optitrack_5',

               '/data/datasets/tello/optitrack_6',
               ]
        split: ['seq01_split.txt', 
                'seq02_split.txt', 
                'seq03_split.txt', 
                'seq05_split.txt',
                'seq06_split.txt',

                'jw_dh_desk_part1.txt',
                'jw_dh_desk_part2.txt',
                'jw_dh_desk_part3.txt',
                'jw_dh_desk_part4.txt',
                
                'my_desk_part1.txt',
                'my_desk_part2.txt',
                
                'workbench_boxes_low_alt_part1.txt',
                'workbench_boxes_low_alt_part2.txt',
                
                'workbench_boxes_low_alt_2_part1.txt',
                'workbench_boxes_low_alt_2_part2.txt',
                
                'workbench_with_boxes_part1.txt',
                'workbench_with_boxes_part2.txt',
                'workbench_with_boxes_part3.txt',
                
                'optitrack_1_part1.txt',

                'optitrack_2_part1.txt',
                'optitrack_2_part2.txt',

                'optitrack_3_part1.txt',

                'optitrack_4_part1.txt',

                'optitrack_5_part1.txt',
                'optitrack_5_part1.txt',

                'optitrack_6_part1.txt'
                ]
        repeat: [3]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/tello/optitrack_1',
               '/data/datasets/tello/optitrack_3',
               '/data/datasets/tello/optitrack_4',
               '/data/datasets/tello/aigc']
        split: ['optitrack_1_part1.txt',
                'optitrack_3_part2.txt',
                'optitrack_4_part1.txt',
                'seq04_split.txt']
    # test:
    #     dataset: ['KITTI']
    #     path: ['/data/datasets/rolling_shutter_rect']
    #     split: ['seq04_split.txt']

wandb:
    dry_run: False
