set(_CATKIN_CURRENT_PACKAGE "rmtt_driver")
set(rmtt_driver_VERSION "0.0.0")
set(rmtt_driver_MAINTAINER "tianbot <tianbot@todo.todo>")
set(rmtt_driver_PACKAGE_FORMAT "2")
set(rmtt_driver_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_driver_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_driver_BUILDTOOL_DEPENDS "catkin")
set(rmtt_driver_BUILDTOOL_EXPORT_DEPENDS )
set(rmtt_driver_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_driver_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(rmtt_driver_TEST_DEPENDS )
set(rmtt_driver_DOC_DEPENDS )
set(rmtt_driver_URL_WEBSITE "")
set(rmtt_driver_URL_BUGTRACKER "")
set(rmtt_driver_URL_REPOSITORY "")
set(rmtt_driver_DEPRECATED "")